title: MATH 2740 (Math of Data Science)
logo: /assets/img/PCA_plot_of_European_individuals.png
description: This is the material for when I (Julien Arino) am teaching the course.
show_downloads: true
theme: jekyll-theme-minimal
google_analytics: UA-1943806-8
plugins:
  - jekyll-sitemap
